language: generic 
# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test

sudo: required
services:
  - docker

before_install:
  - docker build -t youngchullim/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true USERNAME/docker-react npm run test
